from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^$',views.index,name='index'),
    url(r'^logout/', views.logout_,name='logout'),
    url(r'^login/', views.login_,name='login'),
    url(r'^registration/', views.registration_,name='registration'),
    url(r'^myprofile/', views.myprofile,name='myprofile'),
    url(r'^makeperiod/', views.makeperiod,name='makeperiod'),
    url(r'^maketariffe/', views.maketariffe,name='maketariffe'),
    url(r'^maketipi/', views.maketipi,name='maketipi'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/validate_password/$', views.validate_password, name='validate_password'),
    url(r'^ajax/validate_period/$', views.validate_period, name='validate_period'),
    url(r'^addroom/', views.addroom,name='addroom'),
    url(r'^viewroom/', views.viewroom,name='viewroom'),
    url(r'^room/(?P<room_id>\d+)/$', views.info_room, name='info_room'),
    url(r'^modifyroom/(?P<room_id>\d+)/$', views.modify_room, name='modify_room'),
    url(r'^eliminateroom/(?P<room_id>\d+)/$', views.eliminate_room,name ='eliminate_room'),
    url(r'^tableau/', views.tableau,name='tableau'),
    url(r'^rubrica/', views.rubrica,name='rubrica'),
    url(r'^addclienti/', views.addclienti,name='addclienti'),
    url(r'^client/(?P<client_id>\d+)/$', views.info_client,name='info_client'),
    url(r'^modifyclient/(?P<client_id>\d+)/$', views.modify_client,name='modify_client'),
    url(r'^eliminateclient/(?P<client_id>\d+)/$', views.eliminate_client,name='eliminate_client'),
    url(r'^payment/', views.payment,name='payment'),
    url(r'^prenotazioni/', views.prenotazioni,name='prenotazioni'),
    url(r'^addprenotazione/', views.addprenotazione,name='addprenotazione'),
    url(r'^addprenotazione2/', views.addprenotazione2,name='addprenotazione2'),
    url(r'^addprenotazione3/', views.addprenotazione3,name='addprenotazione3'),
    url(r'^addprenotazione4/', views.addprenotazione4,name='addprenotazione4'),
    url(r'^prenotazione/(?P<prenotazione_id>\d+)/$', views.info_prenotazione,name='info_prenotazione'),
    url(r'^eliminateprenotazione/(?P<prenotazione_id>\d+)/$', views.eliminate_prenotazione,name='eliminate_prenotazione'),
    url(r'^note/', views.note,name='note'),
    url(r'^impostazioni/', views.impostazioni,name='impostazioni'),
    url(r'^eliminatenotecamera/(?P<note_id>\d+)/$', views.eliminate_note_camera,name='eliminate_note_camera'),
    url(r'^eliminatenoteclient/(?P<note_id>\d+)/$', views.eliminate_note_client,name='eliminate_note_client'),
    url(r'^eliminatenoteprenotazione/(?P<note_id>\d+)/$', views.eliminate_note_prenotazione,name='eliminate_note_prenotazione'),
    url(r'^add_sconto/', views.add_sconto,name='add_sconto'),
    url(r'^add_extra/', views.add_extra,name='add_extra'),
    url(r'^eliminate_sconto/(?P<sconto_id>\d+)/$', views.eliminate_sconto,name='eliminate_sconto'),
    url(r'^eliminate_extra/(?P<extra_id>\d+)/$', views.eliminate_extra,name='eliminate_extra'),
    url(r'^eliminatescontofromprenotazione/(?P<sconto_id>\d+)/$',views.eliminatescontofromprenotazione,name='eliminatescontofromprenotazione'),                  
    url(r'^eliminatextrafromprenotazione/(?P<extra_id>\d+)/$',views.eliminatextrafromprenotazione,name='eliminatextrafromprenotazione'),
    url(r'^extra/', views.extra,name='extra'),
    url(r'^sconti/', views.sconti,name='sconti'),
)